### ISSUE TITLE
修改数据出现 Array to string conversion 错误

### ISSUE THREAD

**Issue by faizel-88** [Chance-fyi/log#1]
### 我用的环境是
- PHP 版本：7.2
- Laravel 版本：7.0
- chance-fyi/operation-log：2.0.2

### 问题及现象
在更新一个表字段的时候报错 ErrorException: Array to string conversion in file E:\faxunbao\faxunbao-oa\vendor\chance-fyi\operation-log\src\orm\illuminate\Log.php on line 91

发送请求的字段格式是  application/json ，字段类型是 array。
![image](https://user-images.githubusercontent.com/104959361/196921591-94e5d9d2-364e-4202-82f7-9f6c5c8e1256.png)

### 排错及修改建议
根据堆栈找到 vendor\chance-fyi\operation-log\src\orm\illuminate\Log.php 文件下的 getValue 方法没有对字段是 array 类型进行兼容；可对字段类型为 array 进行 json转换。
![image](https://user-images.githubusercontent.com/104959361/196922859-5d05ed7b-6d69-424b-88b8-3b5f7244d7f7.png)

**Comment by Chance-fyi** [comment]
感谢反馈，已经修复，请更新到 v2.0.3

**Comment by diankemao** [comment]
> 感谢反馈，已经修复，请更新到 v2.0.3

支持hyperf吗  hyperf是Laravel 的 ORM
